receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318

exporters:
  debug:
    verbosity: detailed
  otlp_http/logs:
    endpoint: "https://logs-prod-043.grafana.net/otlp"
    headers:
      Authorization: "Basic ${LOKI_AUTH}"

service:
  pipelines:
    logs:
      receivers: [otlp]
      exporters: [debug, otlp_http/logs]
